### ISSUE TITLE
Which one should I use?

### ISSUE THREAD

**Issue by tomek-he-him** [fp-js/fd-curry#2]
Hi @stoeffel, I need to curry a function.

So I’ve found this **[curry](https://www.npmjs.com/package/curry)** thing which looks like the community’s choice since long ago.

But I see there’s this one – newer than _curry_. And there’s **[chickencurry](https://www.npmjs.com/package/chickencurry)** – even newer, as far as I can tell.

Are there any differences? Which one do you maintain? How about writing that down in the readme?

**Comment by stoeffel** [comment]
Would be cool if you would use chickencurry. Feedback and contrib is more
than welcome. And if you like I will add you as a maintainer:-)

**Comment by tomek-he-him** [comment]
Thanks :)

The thing is, I really think it’s best when there’s one well-regarded module for one task. That makes for a healthy, living ecosystem. That’s what we want.

https://en.wikipedia.org/wiki/Not_invented_here – that’s what we don’t want.

I recently had a conversation which made me change my mind in a couple of matters. And this statement holds the essence: https://github.com/mattdesl/module-best-practices/pull/2#issuecomment-121116887.

I just wanted to ask: what led you to creating another module? If it’s a new better way of doing things, I’d love to use that – and contribute if necessary.

**Comment by hemanth** [comment]
[Related](https://github.com/sindresorhus/ama/issues/10) but the major problem is about avoiding duplication, there are many modules which are solving the same problem, but only few solve them very well.

**Comment by stoeffel** [comment]
I often see my self creating a module not because I think I will solve it better or in a new way, but I think it's fun and a good training to solve problems. That's the reason I often don't care if there is already a module. My main goal with chickencurry was to try to implement ramda-like currying (with placeholders).

**Comment by tomek-he-him** [comment]
> only few solve them very well

Exactly! Here’s an idea I came up with – perhaps the way to go for things like lodash or our 1-liners:

> Perhaps something similar to what @serapath suggests isn’t a bad idea after all. Not on developer basis (I’d still prefer to install once@2.0 than @serapath/stack@21.0/once) but on toolbelt basis. For example trine might just be a collection of external modules which follow the “data as this” convention. Ramda would be a set of modules “auto-curried, data as the last parameter”.
> — https://github.com/mattdesl/module-best-practices/pull/2#issuecomment-121160309

And here’s an issue I created today, hoping to start a discussion: https://github.com/mattdesl/module-best-practices/issues/7. Funnily enough @hemanth – it’s exactly the same thing you mentioned that’s on my mind lately.

**Comment by tomek-he-him** [comment]
> My main goal with chickencurry was to try to implement ramda-like currying (with placeholders).

Good stuff! Intuitive and helps avoid [crazy](https://github.com/dominictarr/curry/tree/3f1ca1454368a6561739843ae57e08d6b62d7086#curryto) [complicated](https://github.com/dominictarr/curry/tree/3f1ca1454368a6561739843ae57e08d6b62d7086#curryadapt) [APIs](https://github.com/dominictarr/curry/tree/3f1ca1454368a6561739843ae57e08d6b62d7086#curryadaptto).

And the function bind syntax looks good.

These two things may be the perfect selling point! Maybe instead of `curry3`, `curry5` and `curryN` just the placeholder syntax would do? `add::curryN(3, 8) → add::curry(8, _, _)`?

**Comment by stoeffel** [comment]
>  Maybe instead of curry3, curry5 andcurryN just the placeholder syntax
> would do?add::curryN(3, 8) → add::curry(8, _, _)?

:+1: totally let's do this.

**Comment by tomek-he-him** [comment]
:+1: :+1:

**Comment by tomek-he-him** [comment]
I’m in :D I have a spare hour and a half today, I hope we’ll manage!

**Comment by stoeffel** [comment]
@tomekwi btw you already are a maintainer:smiley:

**Comment by hemanth** [comment]
:+1:
